/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.87
 * Generated at: 2024-03-30 14:25:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.include;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class adminEditUser_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta charset=\"UTF-8\" />\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("    <title>Bark</title>\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.7.1.js\" integrity=\"sha256-eKhayi8LEQwp4NKxN+CfCh+3qOVUtJn3QNZ0TciWLP4=\" crossorigin=\"anonymous\">\r\n");
      out.write("    </script>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./css/adoptionForm.css\">\r\n");
      out.write("    <style type=\"text/css\">\r\n");
      out.write("    #buttom1 {\r\n");
      out.write("    	height: 10px;\r\n");
      out.write("    }\r\n");
      out.write("    #buttom2 {\r\n");
      out.write("    	height: 10px;\r\n");
      out.write("    }\r\n");
      out.write("    .adoption-form>div>table>tbody>tr>td>select{ \r\n");
      out.write("    	 width: 200px;\r\n");
      out.write("    	\r\n");
      out.write("	}\r\n");
      out.write("	.readonly {\r\n");
      out.write("		background-color:#eeeeee;\r\n");
      out.write("	}\r\n");
      out.write("    </style>\r\n");
      out.write("  </head>\r\n");
      out.write("  <body>\r\n");
      dto.UserDTO userDto = null;
      userDto = (dto.UserDTO) _jspx_page_context.getAttribute("userDto", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (userDto == null){
        userDto = new dto.UserDTO();
        _jspx_page_context.setAttribute("userDto", userDto, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write('\r');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.introspect(_jspx_page_context.findAttribute("userDto"), request);
      out.write('\r');
      out.write('\n');

/* 
String id = request.getParameter("id");
UserDao userDao = new UserDao(application);
Board board = dao.read(Integer.parseInt(bno));
dao.close();
*/
request.setAttribute("userDto", userDto);

      out.write("\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("	<div class=\"adoption-title\"><h1>회원 정보 변경</h1></div>\r\n");
      out.write("	<div class=\"adoption\">\r\n");
      out.write("    <form method=\"post\" action=\"#\" class=\"adoption-form\">\r\n");
      out.write("\r\n");
      out.write("    	<div class=\"firstform\">\r\n");
      out.write("		<table> \r\n");
      out.write("			<tr>\r\n");
      out.write("				<td>아이디</td>\r\n");
      out.write("				<td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userDto.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("		</table>\r\n");
      out.write("		</div>\r\n");
      out.write("		<br>\r\n");
      out.write("    	<div class=\"firstform\">\r\n");
      out.write("		<table> \r\n");
      out.write("			<tr>\r\n");
      out.write("				<td>이름</td>\r\n");
      out.write("				<td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userDto.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("		</table>\r\n");
      out.write("		</div>\r\n");
      out.write("		<br>\r\n");
      out.write("    	<div class=\"firstform\">\r\n");
      out.write("		<table> \r\n");
      out.write("			<tr>\r\n");
      out.write("				<td>이메일</td>\r\n");
      out.write("				<td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userDto.email}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("		</table>\r\n");
      out.write("		</div>\r\n");
      out.write("		<br>\r\n");
      out.write("    	<div class=\"firstform\">\r\n");
      out.write("		<table> \r\n");
      out.write("			<tr>\r\n");
      out.write("				<td>연락처</td>\r\n");
      out.write("				<td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userDto.phone}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("		</table>\r\n");
      out.write("		</div>\r\n");
      out.write("		<br>\r\n");
      out.write("    	<div class=\"firstform\">\r\n");
      out.write("		<table> \r\n");
      out.write("			<tr>\r\n");
      out.write("				<td>성별</td>\r\n");
      out.write("				<td><select  name=\"gender\" id=\"gender\">\r\n");
      out.write("						<option value=\"1\">남</option>\r\n");
      out.write("						<option value=\"2\">여</option>\r\n");
      out.write("						<option value=\"3\">미공개</option>\r\n");
      out.write("					</select>\r\n");
      out.write("			</tr>\r\n");
      out.write("		</table>\r\n");
      out.write("		</div>\r\n");
      out.write("		<br>\r\n");
      out.write("    	<div class=\"firstform\">\r\n");
      out.write("		<table> \r\n");
      out.write("			<tr>\r\n");
      out.write("				<td>회원구분</td>\r\n");
      out.write("				<td><select  name=\"gubun\" id=\"gubun\">\r\n");
      out.write("						<option value=\"1\" >개인회원</option>\r\n");
      out.write("						<option value=\"2\" >보호소회원</option>\r\n");
      out.write("						<option value=\"3\" >직원</option>\r\n");
      out.write("					</select>\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("		</table>\r\n");
      out.write("		</div>\r\n");
      out.write("		<br>\r\n");
      out.write("    	<div class=\"firstform\">\r\n");
      out.write("		<table> \r\n");
      out.write("			<tr>\r\n");
      out.write("				<td>회원등급</td>\r\n");
      out.write("				<td><select name=\"grade\" id=\"grade\" >\r\n");
      out.write("						<option id=\"grade1\" value=\"1\">우수</option>\r\n");
      out.write("						<option id=\"grade2\" value=\"2\">일반</option>\r\n");
      out.write("						<option id=\"grade3\" value=\"3\">불량</option>\r\n");
      out.write("					</select>\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("		</table>\r\n");
      out.write("		</div>		\r\n");
      out.write("		\r\n");
      out.write("		<div class=\"adoption-button\" id=\"buttom1\">\r\n");
      out.write("\r\n");
      out.write("        	보호소회원 처리 : <input name=\"button1\" type=\"submit\" value=\"가입승인\"> \r\n");
      out.write("                		  <input name=\"button2\" type=\"submit\" value=\"가입거절\">\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"adoption-button\" id=\"buttom2\">\r\n");
      out.write("                <input name=\"button3\" type=\"submit\" value=\"수정\"> \r\n");
      out.write("                <input name=\"button4\" type=\"submit\" value=\"삭제\">\r\n");
      out.write("        </div>\r\n");
      out.write("	</form>\r\n");
      out.write("	</div>\r\n");
      out.write("</div>\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("	$(document).ready(function () {\r\n");
      out.write("\r\n");
      out.write("		let gender = ");
      out.print(request.getParameter("gender"));
      out.write(";\r\n");
      out.write(" 		switch (gender) {\r\n");
      out.write("		case 1 : 	$(\"#gender\").val(\"1\").prop(\"selected\", true);\r\n");
      out.write("					$(\"#gender\").attr(\"disabled\",true);\r\n");
      out.write("					break;\r\n");
      out.write("		case 2 : 	$(\"#gender\").val(\"2\").prop(\"selected\", true);\r\n");
      out.write("					$(\"#gender\").attr(\"disabled\",true);\r\n");
      out.write("					break;\r\n");
      out.write("		case 3 : 	$(\"#gender\").val(\"3\").prop(\"selected\", true);\r\n");
      out.write("					$(\"#gender\").attr(\"disabled\",true);\r\n");
      out.write("					break;\r\n");
      out.write("		}\r\n");
      out.write(" 		\r\n");
      out.write("		let gubun = ");
      out.print(request.getParameter("gubun"));
      out.write(";\r\n");
      out.write(" 		switch (gubun) {\r\n");
      out.write("		case 1 : 	$(\"#gubun\").val(\"1\").prop(\"selected\", true);\r\n");
      out.write("					$(\"#gubun\").attr(\"disabled\",true);\r\n");
      out.write("					break;\r\n");
      out.write("		case 2 : 	$(\"#gubun\").val(\"2\").prop(\"selected\", true);\r\n");
      out.write("					$(\"#gubun\").attr(\"disabled\",true);\r\n");
      out.write("					break;\r\n");
      out.write("		case 3 : 	$(\"#gubun\").val(\"3\").prop(\"selected\", true);\r\n");
      out.write("					$(\"#gubun\").attr(\"disabled\",true);\r\n");
      out.write("					break;\r\n");
      out.write("		}\r\n");
      out.write(" 		\r\n");
      out.write(" 		if (gubun == \"2\" ) {\r\n");
      out.write(" 			$(\"#buttom1\").css('visibility', 'visible');\r\n");
      out.write(" 		}\r\n");
      out.write(" 		else {\r\n");
      out.write(" 			$(\"#buttom1\").css('visibility', 'hidden');\r\n");
      out.write(" 		}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
