/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.87
 * Generated at: 2024-03-28 17:09:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.include;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class manageDonation_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1711463953601L));
    _jspx_dependants.put("jar:file:/G:/내%20드라이브/Coding/MultiCampus/Semi-project/github/java_workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Bark/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta charset=\"UTF-8\" />\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("    <title>Document</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./css/manageDonation.css\" />\r\n");
      out.write("  </head>\r\n");
      out.write("  <body>\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <div class=\"row\">\r\n");
      out.write("        <div class=\"menu\">\r\n");
      out.write("          <div class=\"sub-menu\">\r\n");
      out.write("            <h><a href=\"#\">회원조회</a></h>\r\n");
      out.write("            <h><a href=\"#\">회원정보변경</a></h>\r\n");
      out.write("            <h>기부금관리</h>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"main-menu\">\r\n");
      out.write("            <h>기부금 관리</h>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"notice_up\">\r\n");
      out.write("          <form action=\"#\" method=\"post\" class=\"notice_searchform\">\r\n");
      out.write("            <select name=\"notice_Categori\">\r\n");
      out.write("              <option>---전체---</option>\r\n");
      out.write("              <option value=\"1\">회원ID</option>\r\n");
      out.write("              <option value=\"1\">보호소명</option>\r\n");
      out.write("            </select>\r\n");
      out.write("            <input type=\"search\" class=\"notice-search\" />\r\n");
      out.write("            <input type=\"submit\" class=\"notice-search-submit\" value=\"검색\" />\r\n");
      out.write("          </form>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"table\">\r\n");
      out.write("          <table class=\"noticetable\">\r\n");
      out.write("            <thead>\r\n");
      out.write("              <tr>\r\n");
      out.write("                <th>No</th>\r\n");
      out.write("                <th>회원ID</th>\r\n");
      out.write("                <th>기부금액</th>\r\n");
      out.write("                <th>기부일</th>\r\n");
      out.write("                <th>보호소</th>\r\n");
      out.write("                <th>\r\n");
      out.write("                  <select>\r\n");
      out.write("                    <option>기부상태</option>\r\n");
      out.write("                    <option>처리완료</option>\r\n");
      out.write("                    <option>처리중</option>\r\n");
      out.write("                    <option>처리실패</option>\r\n");
      out.write("                  </select>\r\n");
      out.write("                </th>\r\n");
      out.write("                <th>보호소 연락처</th>\r\n");
      out.write("              </tr>\r\n");
      out.write("            </thead>\r\n");
      out.write("            <tbody>\r\n");
      out.write("              <tr>\r\n");
      out.write("                <td>1</td>\r\n");
      out.write("                <td><a href=\"#\">wlgus8846</a></td>\r\n");
      out.write("                <td>1,000,000</td>\r\n");
      out.write("                <td>2024-03-24</td>\r\n");
      out.write("                <td>2조보호소</td>\r\n");
      out.write("                <td>처리중</td>\r\n");
      out.write("                <td>02-0000-0000</td>\r\n");
      out.write("              </tr>\r\n");
      out.write("              <tr>\r\n");
      out.write("                <td></td>\r\n");
      out.write("                <td></td>\r\n");
      out.write("                <td></td>\r\n");
      out.write("                <td></td>\r\n");
      out.write("                <td></td>\r\n");
      out.write("                <td></td>\r\n");
      out.write("                <td></td>\r\n");
      out.write("              </tr>\r\n");
      out.write("              <tr>\r\n");
      out.write("                <td></td>\r\n");
      out.write("                <td></td>\r\n");
      out.write("                <td></td>\r\n");
      out.write("                <td></td>\r\n");
      out.write("                <td></td>\r\n");
      out.write("                <td></td>\r\n");
      out.write("                <td></td>\r\n");
      out.write("              </tr>\r\n");
      out.write("              <tr>\r\n");
      out.write("                <td></td>\r\n");
      out.write("                <td></td>\r\n");
      out.write("                <td></td>\r\n");
      out.write("                <td></td>\r\n");
      out.write("                <td></td>\r\n");
      out.write("                <td></td>\r\n");
      out.write("                <td></td>\r\n");
      out.write("              </tr>\r\n");
      out.write("              <tr>\r\n");
      out.write("                <td></td>\r\n");
      out.write("                <td></td>\r\n");
      out.write("                <td></td>\r\n");
      out.write("                <td></td>\r\n");
      out.write("                <td></td>\r\n");
      out.write("                <td></td>\r\n");
      out.write("                <td></td>\r\n");
      out.write("              </tr>\r\n");
      out.write("              <tr>\r\n");
      out.write("                <td></td>\r\n");
      out.write("                <td></td>\r\n");
      out.write("                <td></td>\r\n");
      out.write("                <td></td>\r\n");
      out.write("                <td></td>\r\n");
      out.write("                <td></td>\r\n");
      out.write("                <td></td>\r\n");
      out.write("              </tr>\r\n");
      out.write("              <tr>\r\n");
      out.write("                <td></td>\r\n");
      out.write("                <td></td>\r\n");
      out.write("                <td></td>\r\n");
      out.write("                <td></td>\r\n");
      out.write("                <td></td>\r\n");
      out.write("                <td></td>\r\n");
      out.write("                <td></td>\r\n");
      out.write("              </tr>\r\n");
      out.write("              <tr>\r\n");
      out.write("                <td></td>\r\n");
      out.write("                <td></td>\r\n");
      out.write("                <td></td>\r\n");
      out.write("                <td></td>\r\n");
      out.write("                <td></td>\r\n");
      out.write("                <td></td>\r\n");
      out.write("                <td></td>\r\n");
      out.write("              </tr>\r\n");
      out.write("              <tr>\r\n");
      out.write("                <td></td>\r\n");
      out.write("                <td></td>\r\n");
      out.write("                <td></td>\r\n");
      out.write("                <td></td>\r\n");
      out.write("                <td></td>\r\n");
      out.write("                <td></td>\r\n");
      out.write("                <td></td>\r\n");
      out.write("              </tr>\r\n");
      out.write("              <tr>\r\n");
      out.write("                <td></td>\r\n");
      out.write("                <td></td>\r\n");
      out.write("                <td></td>\r\n");
      out.write("                <td></td>\r\n");
      out.write("                <td></td>\r\n");
      out.write("                <td></td>\r\n");
      out.write("                <td></td>\r\n");
      out.write("              </tr>\r\n");
      out.write("              <tr>\r\n");
      out.write("                <td></td>\r\n");
      out.write("                <td></td>\r\n");
      out.write("                <td></td>\r\n");
      out.write("                <td></td>\r\n");
      out.write("                <td></td>\r\n");
      out.write("                <td></td>\r\n");
      out.write("                <td></td>\r\n");
      out.write("              </tr>\r\n");
      out.write("              <tr>\r\n");
      out.write("                <td></td>\r\n");
      out.write("                <td></td>\r\n");
      out.write("                <td></td>\r\n");
      out.write("                <td></td>\r\n");
      out.write("                <td></td>\r\n");
      out.write("                <td></td>\r\n");
      out.write("                <td></td>\r\n");
      out.write("              </tr>\r\n");
      out.write("            </tbody>\r\n");
      out.write("          </table>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"pageNumber\">\r\n");
      out.write("          <a href=\"#\"><</a>\r\n");
      out.write("          <a href=\"#\">1</a>\r\n");
      out.write("          <a href=\"#\">2</a>\r\n");
      out.write("          <a href=\"#\">3</a>\r\n");
      out.write("          <a href=\"#\">></a>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
